const state = {
    columnWidthMap: {
        weightKg: '120',
        vehicleLength: '120',
        lane: '80',
        axleCount: '100',
        speed: '80',
        temperature: '100',
        direction: '80',
        crossLane: '80',
        type: '100',
        axleWeight1: '120',
        axleWeight2: '120',
        axleWeight3: '120',
        axleWeight4: '120',
        axleWeight5: '120',
        axleWeight6: '120',
        wheelbase1: '120',
        wheelbase2: '120',
        wheelbase3: '120',
        wheelbase4: '120',
        wheelbase5: '120',
        vehicleTypeCode: '120',
        vehicleType: '120',
        axle1Kn: '100',
        axle2Kn: '100',
        axle3Kn: '100',
        offset: '100',
        ambientTemperature: '120',
        temperature1: '120',
        dewPointTemperature: '140',
        ambientHumidity: '120',
        airPressure: '120',
        totalRadiation1Instant: '160',
        uvradiationInstant: '160',
        windDirection: '120',
        instantWindSpeed: '140',
        windSpeed2Min: '140',
        windSpeed10Min: '140',
        rainfallIntervalAccumulated: '160',
        rainfallDailyAccumulated: '160',
        totalRadiation1DailyAccumulated: '180',
        uvradiationDailyAccumulated: '180',
        illuminance: '120',
        voltage: '120',
        applyId: '150',
        userId: '150',
        dataType: '150',
        fields: '200',
        startTime: '180',
        stopTime: '180',
        status: '100',
        userEmail: '180',
        msg: '120',
    },
    columnLabelMap: {
        id: "编号",
        timestamp: "时间",
        weightKg: "总重KG",
        vehicleLength: "车长",
        lane: "车道",
        axleCount: "轴数",
        speed: "速度",
        temperature: "温度",
        direction: "方向",
        crossLane: "跨道",
        type: "类型",
        axleWeight1: "轴重1",
        axleWeight2: "轴重2",
        axleWeight3: "轴重3",
        axleWeight4: "轴重4",
        axleWeight5: "轴重5",
        axleWeight6: "轴重6",
        wheelbase1: "轴距1",
        wheelbase2: "轴距2",
        wheelbase3: "轴距3",
        wheelbase4: "轴距4",
        wheelbase5: "轴距5",
        vehicleTypeCode: "车型编号",
        vehicleType: "车型",
        axle1Kn: "轴1KN",
        axle2Kn: "轴2KN",
        axle3Kn: "轴3KN",
        offset: "偏移",
        timestamp: "时间",
        ambientTemperature: "环温(℃)",
        temperature1: "温度1(℃)",
        dewPointTemperature: "露点温度(℃)",
        ambientHumidity: "环湿(%RH)",
        airPressure: "气压(hPa)",
        totalRadiation1Instant: "总辐射1瞬时(W/㎡)",
        uvradiationInstant: "紫外辐射瞬时(W/㎡)",
        windDirection: "风向(°)",
        instantWindSpeed: "瞬时风速(m/s)",
        windSpeed2Min: "2分钟风速(m/s)",
        windSpeed10Min: "10分钟风速(m/s)",
        rainfallIntervalAccumulated: "雨量间隔累计(mm)",
        rainfallDailyAccumulated: "雨量日累计(mm)",
        totalRadiation1DailyAccumulated: "总辐射1日累计(MJ/㎡)",
        uvradiationDailyAccumulated: "紫外辐射日累计(MJ/㎡)",
        illuminance: "光照度(KLux)",
        voltage: "电量(V)",
        applyId: '申请ID',
        userId: '用户ID',
        dataType: '数据类型',
        fields: '数据项名称',
        startTime: '开始时间',
        stopTime: '结束时间',
        status: '状态',
        userEmail: '用户邮箱',
        msg: '附加信息',
    },
};

const getters = {
    getColumnWidth: (state) => (key) => {
        return state.columnWidthMap[key] || '150'; // 默认宽度为 150
    },
    getColumnLabel: (state) => (key) => {
        return state.columnLabelMap[key] || key; // 如果没有找到对应映射，返回字段名
    },
};

export default {
    namespaced: true, // 启用命名空间
    state,
    getters,
};